submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 50
cpus_per_task: 2
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
mem_per_gpu: null
mem_per_cpu: 10240
account: ls_krausea
# additional_parameters: {"gpus": "rtx_4090:1", "account": "ls_krausea"}
additional_parameters: {"gres": "gpumem:10g", "gpus":1}
array_parallelism: 256
max_num_timeout: 100
setup:
  - '#SBATCH --requeue'